### ISSUE TITLE
Compiling shaders fails on macOS

### ISSUE THREAD

**Issue by Jylhis** [Zalasus/opendrakan#3]
macOS seems to support only OpenGL 2.1 or 3.2 core, and after OS X 10.9 versions 3.3 and 4.1.

https://stackoverflow.com/questions/20264814/glsl-version-130-on-mac-os-x-causes-error

```
VERTEX glCompileShader "default_vertex.glsl" FAILED
VERTEX Shader "default_vertex.glsl" infolog:
ERROR: 0:3: '' :  version '130' is not supported
```

**Comment by Zalasus** [comment]
Downgraded to GLSL 1.20 / OpenGl 2.1 in 9e4d4b90983af029ccd8553c2839a0931dd3d66f.

Can't test whether this resolves the issue as I don't have access to any macOS machines right now.

**Comment by Jylhis** [comment]
It works
