### ISSUE TITLE
Graphics broken on Windows

### ISSUE THREAD

**Issue by Zalasus** [Zalasus/opendrakan#6]
Shaders seem to work to some degree. See report [here](https://arokhslair.net/forum/viewtopic.php?p=33124#p33124).

Can't reproduce as of now as I don't have a working Windows build environment.

This problem might be related to OSG's attribute and uniform aliasing (see above report). Going to investigate this further.

**Comment by Zalasus** [comment]
Disabling the uniform and attribute aliasing produced results very much like the ones in the referenced forum post. 

Revision 615a679e248c5b3a8aad3b6916fa1e3d1cbb395f removed the necessity for aliasing, which might fix the issue.

Awaiting testing.

**Comment by UCyborg** [comment]
Works properly now! Multi-monitor crash is also gone.

**Comment by Zalasus** [comment]
Great! Closing this issue.
