### ISSUE TITLE
Some layer textures mapped incorrectly

### ISSUE THREAD

**Issue by Zalasus** [Zalasus/opendrakan#7]
In some places, layer textures aren't mapped correctly. They appear either rotated, mirrored or have seams that aren't visible in the original game.

One instance of this occurs in the Ruined Village level, on the road leaving the village to the right.

It could be possible we simply mess up all texture orientations and just by chance it works anyway most of the time, or there are mechanisms in layer texture mapping we don't fully understand yet.

The engine stores layers as cells, each consisting of two triangles. Every triangle can have it's own texture, but UV coordinates are shared among the two vertices defining the cell's diagonal.

Relevant lines are:
[Loading texture coordinates from file](https://github.com/Zalasus/opendrakan/blob/dc2022aebaf2420e1ba12460170a94a9561b9e7e/src/Layer.cpp#L109)
[Assigning coordinates to cell's corners](https://github.com/Zalasus/opendrakan/blob/dc2022aebaf2420e1ba12460170a94a9561b9e7e/src/Layer.cpp#L179)

**Comment by Jylhis** [comment]
There is also problem loading textures in ruined village, inside the tavern. Most of the textures aren't loaded in the big room. Not sure if it's related to this.

**Comment by Zalasus** [comment]
I don't think these effects are related. The tavern definitely had an interior at some point. I can even recall matching the orientation of the plates on the floor. This is different bug that I introduced without noticing. Thanks for the pointer!

**Comment by Zalasus** [comment]
Okay, I just found out that that is not a bug at all. For some reason, the tavern's interior is hidden using a timer upon loading the map, and only once the player steps through the trigger at the entrance it is toggled by a Visibility Toggler object. I implemented the Toggler and Timer recently, but not the trigger that would cause the interior to be made visible.

**Comment by Jylhis** [comment]
Okay, that explains it.

**Comment by Zalasus** [comment]
Adressed this in f83dc7c. 

The issue was that I interpreted the coordinate array as UVUVUVUV, when in fact it should be UUUUVVVV.
